[deps]
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[Genie]
instantiated_pwd = "c:\\Users\\kaele\\OneDrive\\Documents\\Kaelen's stuff\\SUTD\\TERM 5\\2D\\Term 5 2D Project\\practice3"
